server:
  port: 6662
spring:
  datasource:
    username: root
    #password: hnlpruanjian2019!@#iop121
    #password: Lysoft%$#@!
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tt?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


netty:
  client:
    clientNo: client-0002
  server:
    port: 9999